version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=mysql://root:taxi@web-db:3306/web_dev
      - DATABASE_TEST_URL=mysql://root:taxi@web-db:3306/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
      args:
        MARIADB_USER: joe
        MARIADB_PASSWORD: taxi
    expose:
      - 3306
    environment:
      - MARIADB_USER=joe
      - MARIADB_PASSWORD=taxi
      - MARIADB_ROOT_PASSWORD=taxi
